// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Post      string
	UserID    uuid.UUID
}

type User struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Name            string
	Password        string
	ApiKey          string
	ApiKeyExpiresAt time.Time
}

type UsersKey struct {
	ID                    uuid.UUID
	CreatedAt             time.Time
	AccessTokenExpiresAt  time.Time
	RefreshToken          string
	RefreshTokenExpiresAt time.Time
	UserID                uuid.UUID
}
