// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Post struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Post      string
	UserID    string
}

type User struct {
	ID              string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Name            string
	Password        string
	ApiKey          string
	ApiKeyExpiresAt time.Time
}

type UsersKey struct {
	ID                    string
	CreatedAt             time.Time
	AccessTokenExpiresAt  time.Time
	RefreshToken          string
	RefreshTokenExpiresAt time.Time
	UserID                string
}
