// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Post struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Post      string
	UserID    string
}

type User struct {
	ID              string
	CreatedAt       string
	UpdatedAt       string
	Name            string
	Password        string
	ApiKey          string
	ApiKeyExpiresAt string
}

type UsersKey struct {
	ID                    string
	CreatedAt             string
	AccessTokenExpiresAt  string
	RefreshToken          string
	RefreshTokenExpiresAt string
	UserID                string
}
