// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, name, password, api_key, api_key_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, name, password, api_key, api_key_expires_at
`

type CreateUserParams struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Name            string
	Password        string
	ApiKey          string
	ApiKeyExpiresAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Password,
		arg.ApiKey,
		arg.ApiKeyExpiresAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Password,
		&i.ApiKey,
		&i.ApiKeyExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, created_at, updated_at, name, password, api_key, api_key_expires_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Password,
		&i.ApiKey,
		&i.ApiKeyExpiresAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one

SELECT id, created_at, updated_at, name, password, api_key, api_key_expires_at FROM users WHERE name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Password,
		&i.ApiKey,
		&i.ApiKeyExpiresAt,
	)
	return i, err
}

const updateUserApiKey = `-- name: UpdateUserApiKey :exec

UPDATE users
SET api_key = $1, api_key_expires_at = $2
WHERE id = $3
`

type UpdateUserApiKeyParams struct {
	ApiKey          string
	ApiKeyExpiresAt time.Time
	ID              uuid.UUID
}

func (q *Queries) UpdateUserApiKey(ctx context.Context, arg UpdateUserApiKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateUserApiKey, arg.ApiKey, arg.ApiKeyExpiresAt, arg.ID)
	return err
}
